version: "2.2"
services:
  test_app:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: python3 test_app.py
    ports:
      - "8010:8010"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

    environment:
      - SRVC_CONFIG=etc/local.json
      - SRVC_LOG=etc/logging.conf

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=test_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
